<div class="row">

    <?php if($user): ?>
        <div class="col-md-4">
            <div class="card px-4">
                <?php require_once './templates/form_alta_producto.phtml' ?>
            </div>
        </div>
    <?php endif; ?>

    <div class="col-md-8">
        <ul class="list-group">
            <?php foreach($productos as $producto) { ?>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div class="label">
                        <b><?= htmlspecialchars($producto->nombre) ?></b>
                        <br>
                        <small>Categoría: <?= htmlspecialchars($producto->categoria) ?></small><br>
                        <small>Precio: $<?= number_format($producto->precio, 2) ?></small>
                    </div>

                    <?php if($user): ?>
                        <div class="actions">
                            <a href="editar/<?= $producto->id ?>" class="btn btn-sm btn-warning">EDITAR</a>
                            <a href="eliminar/<?= $producto->id ?>" class="btn btn-sm btn-danger">ELIMINAR</a>
                        </div>
                    <?php endif; ?>
                </li>
            <?php } ?>
        </ul>

        <p class="mt-3">
            <small>Mostrando <?= $count ?> productos</small>
        </p>
    </div>
</div>
